Feature/packages/takeover  #web 0000
Talkdesk/CREAC pull request #263
Opened 2020-12-04 17:31 UTC by Mar0cas

2020-12-04 17:33 UTC, rebecatalkdesk commented on packages/organisms/takeover/package.json
> +    "@creat/common": "^1.0.3",
If you need the new changes to common for the cookies, this version will need to be bumped to 1.0.4 here and in the common package, or else the takeover won't have the new utils

2020-12-04 17:34 UTC, rebecatalkdesk commented on packages/organisms/takeover/package.json
> +    "@creat/image": "~1.0.3",
Same thing here if you need the svg update.

2020-12-04 18:16 UTC, rebecatalkdesk requested changes
Missing the snapshot

2020-12-04 18:18 UTC, rebecatalkdesk commented on packages/organisms/takeover/src/Takeover.tsx
> +                <i className="icon-ui-arrowlink">
Use the icon atom

2020-12-04 18:21 UTC, rebecatalkdesk commented on packages/organisms/takeover/src/Takeover.tsx
> +            {!ctas || <Buttons cta={ctas} />}
ctas can be an empty array, this only checks if there is the prop right?

2020-12-04 18:26 UTC, Mar0cas commented on packages/organisms/takeover/src/Takeover.tsx
> +            {!ctas || <Buttons cta={ctas} />}
Fixed

2020-12-04 18:36 UTC, Mar0cas commented on packages/organisms/takeover/src/Takeover.tsx
> +                <i className="icon-ui-arrowlink">
fixed

2020-12-10 11:26 UTC, rebecatalkdesk approved these changes

2020-12-10 11:31 UTC, merged