Feature/packages/table #wds 36
Talkdesk/CREAC pull request #271
Opened 2020-12-18 18:01 UTC by LuisConceicaoTD

2020-12-18 19:25 UTC, Mar0cas approved these changes

2020-12-18 19:25 UTC, Mar0cas commented on packages/molecules/table/src/Table.tsx
> +            jobsList.map((job: any, index: number) => {
For the `job` parameter, don't use any type, export `jobList` interface on `./component/Types.ts` file.
Import `jobList` on `./component/index.ts` file and import it on line 4 of this file (`Table.tsx`)
Line 4 goes like this:
```javascript
import { Props, Utils, jobList } from "./component";
```
Line 15:
```javascript
jobsList.map((job: jobList, index: number) => {
```

2020-12-18 19:25 UTC, Mar0cas commented on packages/molecules/table/src/component/index.ts
> +import { Props } from "./Types";
Add `jobList` here so it can be exported on line 4

2020-12-18 19:25 UTC, Mar0cas commented on packages/molecules/table/src/component/index.ts
> +export { Props , Utils };
down here:
```javascript
export { Props , Utils, jobList };  
```

2020-12-29 16:08 UTC, rebecatalkdesk requested changes

2020-12-29 16:08 UTC, rebecatalkdesk commented on packages/molecules/table/src/component/Types.ts
> +  bg_color: Color;
Since this has a default it should be optional `bg_color?: Color;`

2020-12-29 16:08 UTC, rebecatalkdesk commented on packages/molecules/table/src/component/Types.ts
> +  content_color: Color;
Since this has a default it should be optional `content_color?: Color;`

2020-12-29 16:08 UTC, rebecatalkdesk commented on packages/molecules/table/src/component/Types.ts
> +  bg_color: Color;
Since this has a default it should be optional `bg_color?: Color;`

2020-12-29 16:08 UTC, rebecatalkdesk commented on packages/molecules/table/src/component/Types.ts
> +  color: Color;
Since this has a default it should be optional `color?: Color;`

2020-12-29 16:08 UTC, rebecatalkdesk commented on packages/molecules/table/src/component/Utils.ts
> +  var cut = content.indexOf(' ', limit);
No `var`, only `const` or `let`

2020-12-29 16:08 UTC, rebecatalkdesk commented on packages/molecules/table/src/__stories__/Table.stories.tsx
> +    props.bg_color = select('Bg Color', ColorProps, props.bg_color, 'General') as Color;
Add these to the Jobs story too

2020-12-29 16:20 UTC, LuisConceicaoTD commented on packages/molecules/table/src/__stories__/Table.stories.tsx
> +    props.bg_color = select('Bg Color', ColorProps, props.bg_color, 'General') as Color;
Foi intencional não ter adicionado as opções de customização à tabela de jobs porque o estilo dessa é fixo, é uma tabela só usada na careers. Quando quiserem usar uma tabela custom pode se usar a generic

2020-12-29 17:15 UTC, rebecatalkdesk approved these changes

2020-12-29 17:20 UTC, merged