Update/package/button #wa 469
Talkdesk/CREAC pull request #370
Opened 2021-02-09 16:20 UTC by Mar0cas

2021-02-09 16:32 UTC, rebecatalkdesk approved these changes

2021-02-09 17:40 UTC, rebecatalkdesk requested changes

2021-02-09 17:40 UTC, rebecatalkdesk commented on packages/atoms/button/src/component/Types.ts
> +  error: boolean
Will this come in the API for normal CTAs? If not, and since it has a default it should be have the `?` to prevent errors.

2021-02-09 17:40 UTC, rebecatalkdesk commented on packages/atoms/button/src/component/Types.ts
> +  disabled: IsDisabled;
Will this come in the API for normal CTAs?

2021-02-09 18:10 UTC, rebecatalkdesk approved these changes

2021-02-10 10:36 UTC, LuisConceicaoTD approved these changes

2021-02-10 11:56 UTC, merged