Update/packages/pagination #468
Talkdesk/CREAC pull request #380
Opened 2021-02-12 10:33 UTC by rebecatalkdesk

Updated Pagination to prepare to add styles: wa-468
- Added `browserlist` to `package.json`
- Removed unneeded classes
- Added `-primary` to root component classes
- Removing the previous and next page buttons depending on the current page and pages length, instead of adding an invisible class
- Changed mobile page display from `h3` to `span` because the font size was huge
- Incremented `quaternary` role to light theme to use on Pagination

Adding Pagination styles: wa-468 
- Created component color-scheme for themes 
- Removed old scss and created new one for the new styling

Updated Pagination story: wa-468
- Added pagination for each theme
- Created empty mock because of an error

Updated Pagination tests: wa-468
- Updated snapshot because of updated html structure
- Updated tests to reflect new component structure

2021-02-12 11:02 UTC, LuisConceicaoTD approved these changes

2021-02-12 14:03 UTC, Mar0cas requested changes
Please review the pagination flickering when changing pages.
Review with design the state of the `prev` & `next` button, if they are removed from the DOM or if they go to `disabled` state.

2021-02-15 10:29 UTC, Mar0cas requested changes

2021-02-15 10:29 UTC, Mar0cas commented on packages/molecules/pagination/src/Pagination.tsx
>          <div className="col-14 pagination__content">
Remove `col-14` use `col-12`

2021-02-15 10:29 UTC, Mar0cas commented on packages/molecules/pagination/src/styles/Pagination.scss
>  .section__pagination {
In this file, find where we are using margin auto to push prev & next buttons to the outside, and align all elements to the middle.

2021-02-15 10:29 UTC, Mar0cas commented on packages/molecules/pagination/src/Pagination.tsx
> +          <div className="col-10 offset-1 col-sm-8 offset-sm-2 col-md-6 offset-md-3 col-lg-4 offset-lg-4 pagination__content">
Switch all bootstrap classes to `col-12`.

2021-02-17 14:03 UTC, Mar0cas approved these changes

2021-02-18 14:42 UTC, merged